name: Package Install Test

on: [pull_request]

jobs:
  build:
    environment: integ
    runs-on: default
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run package test
        env:
          PINTEREST_REFRESH_ACCESS_TOKEN: ${{ secrets.CI_REFRESH_ACCESS_TOKEN }}
          PINTEREST_APP_SECRET: ${{ secrets.CI_APP_SECRET }}
          PINTEREST_APP_ID: ${{ secrets.CI_APP_ID }}
          PINTEREST_API_URI: ${{ secrets.CI_HOST_URI }}
          PINTEREST_DEFAULT_AD_ACCOUNT_ID: ${{ secrets.CI_DEFAULT_AD_ACCOUNT_ID }}
        run: |
          python -m pip install --upgrade pip
          make test_package
